# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/vsts/pipelines/apps/windows/dot-net

trigger:
- master
- develop
- feature/*
- bugfix/*
- hotfix/*
- greenkeeper/*

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: Npm@1
  displayName: 'Build (back-end)'
  inputs:
    command: 'custom'
    customCommand: 'run build-back'

- task: Npm@1
  displayName: 'Test (back-end)'
  inputs:
    command: 'custom'
    customCommand: 'run test-back'

- task: Npm@1
  displayName: 'npm install (front-end)'
  inputs:
    workingDir: './GoldKeeper/ClientApp/'
    command: 'install'

- task: Npm@1
  displayName: 'Lint (front-end)'
  inputs:
    workingDir: './GoldKeeper/ClientApp/'
    command: 'custom'
    customCommand: 'run lint'

- task: Npm@1
  displayName: 'Build (front-end)'
  inputs:
    workingDir: './GoldKeeper/ClientApp/'
    command: 'custom'
    customCommand: 'run build'

- task: Npm@1
  displayName: 'Test (front-end)'
  inputs:
    workingDir: './GoldKeeper/ClientApp/'
    command: 'custom'
    customCommand: 'run test'

- bash: sh -x ./git-status.sh
  displayName: 'Create GitHub status'
