# Base build definition
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/vsts/pipelines/apps/windows/dot-net

parameters:
  BuildConfiguration: dev

steps:
- task: NuGetToolInstaller@0

- task: DotNetCoreCLI@2
  displayName: Install Nerdbank.GitVersioning tool
  inputs:
    command: custom
    custom: tool
    arguments: install --tool-path . nbgv

- script: nbgv cloud
  displayName: Set Version

- task: Npm@1
  displayName: 'Build (back-end) ${{ parameters.BuildConfiguration }}'
  inputs:
    command: 'custom'
    customCommand: 'run build-back:${{ parameters.BuildConfiguration }}'

- bash: sh -x ./shell/git-status.sh $(goldkeeper.GithubToken)
  displayName: 'Create GitHub status'
