# Build for Greenkeeper
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/vsts/pipelines/apps/windows/dot-net

name: GoldKeeper-CI
trigger:
- nukeeper-*

pool:
  vmImage: 'VS2017-Win2016'

steps:
- task: NuGetToolInstaller@0

- task: Npm@1
  displayName: 'Build (back-end) Dev'
  inputs:
    command: 'custom'
    customCommand: 'run build-back'

- task: Npm@1
  displayName: 'Test (back-end) Dev'
  inputs:
    command: 'custom'
    customCommand: 'run test-back'

- bash: sh -x ./shell/git-status.sh
  displayName: 'Create GitHub status'
