# Build for Development environment
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/vsts/pipelines/apps/windows/dot-net

name: GoldKeeper-CI-DEV
trigger:
- develop
- feature/*
- bugfix/*

pool:
  vmImage: 'VS2017-Win2016'

steps:
- task: DotNetCoreCLI@2  
  displayName: Install Nerdbank.GitVersioning tool
  inputs:
    command: custom
    custom: tool
    arguments: install --tool-path . nbgv

- script: nbgv cloud
  displayName: Set Version

- task: NuGetToolInstaller@0

- task: Npm@1
  displayName: 'Build (back-end) Dev'
  inputs:
    command: 'custom'
    customCommand: 'run build-back'

- task: Npm@1
  displayName: 'Test (back-end) Dev'
  inputs:
    command: 'custom'
    customCommand: 'run test-back'

- task: Npm@1
  displayName: 'npm install (front-end)'
  inputs:
    workingDir: './GoldKeeper/ClientApp/'
    command: 'install'

- task: Npm@1
  displayName: 'Lint (front-end) Dev'
  inputs:
    workingDir: './GoldKeeper/ClientApp/'
    command: 'custom'
    customCommand: 'run lint'

- task: Npm@1
  displayName: 'Build (front-end) Dev'
  inputs:
    workingDir: './GoldKeeper/ClientApp/'
    command: 'custom'
    customCommand: 'run build'

- task: Npm@1
  displayName: 'Test (front-end) Dev'
  inputs:
    workingDir: './GoldKeeper/ClientApp/'
    command: 'custom'
    customCommand: 'run test'

- bash: sh -x ./shell/git-status.sh $(goldkeeper.GithubToken)
  displayName: 'Create GitHub status'
  