# Build for Greenkeeper
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/vsts/pipelines/apps/windows/dot-net

name: GoldKeeper-CI
trigger:
- greenkeeper/*

pool:
  vmImage: 'VS2017-Win2016'

steps:
- task: Npm@1
  displayName: 'npm install (front-end)'
  inputs:
    workingDir: './GoldKeeper/ClientApp/'
    command: 'install'

- task: Npm@1
  displayName: 'Build (front-end) Dev'
  inputs:
    workingDir: './GoldKeeper/ClientApp/'
    command: 'custom'
    customCommand: 'run build'

- task: Npm@1
  displayName: 'Test (front-end) Dev'
  inputs:
    workingDir: './GoldKeeper/ClientApp/'
    command: 'custom'
    customCommand: 'run test'
